language: go

go:
- 1.10.x

go_import_path: github.com/gemalto/helm-spray

install:

script:
- make dist

after_success:
- export TRAVIS_TAG="v1.0"

deploy:
- provider: releases
  api_key: ${GITHUB_API_KEY}
  file: _dist/helm-spray*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
