language: go

go:
  - 1.10.x

go_import_path: github.com/gemalto/helm-spray

install:

script:
- make dist

after_success:
- export TRAVIS_TAG=$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)

before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.email "travis@travis-ci.org"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
- provider: releases
  api_key: ${GITHUB_API_KEY}
  file: _dist/helm-spray*
  skip_cleanup: true
  file_glob: true
  on:
    repo: cvila84/helm-spray
    tags: true
