os: linux

language: go

go:
  - master

go_import_path: github.com/gemalto/helm-spray

script:
  - make test-all
  - make dist

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: _dist/helm-spray*
    skip_cleanup: true
    file_glob: true
    on:
      tags: true