os: linux

language: go

go:
- 1.10.x

go_import_path: github.com/gemalto/helm-spray

script:
  - make dist_linux

deploy:
  - provider: releases
    tag_name: $TRAVIS_TAG
    target_commitish: $TRAVIS_COMMIT
    api_key: $GITHUB_API_KEY
    file: _dist/helm-spray*
    skip_cleanup: true
    file_glob: true
    on:
      repo: cvila84/helm-spray
      tags: true