name: Release on github
on:
  push:
    branches:
      - "github-workflow"
#    tags:
#      - 'v*'
jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/src/github.com/gemalto/helm-spray
      - name: Make release
        run: |
          ls -lR ${{ github.workspace }}
          make dist
